# These are supported funding model platforms

# GitHub Sponsors
github: iAn-P1nt0

# Uncomment and add your username/project for other platforms as needed:
# patreon: your-username
# open_collective: your-project
# ko_fi: your-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-username
# issuehunt: your-username
# otechie: your-username
# lfx_crowdfunding: project-name
# custom: ['https://your-donation-link.com', 'https://another-link.com']
